[package]
name = "ip_update"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
tokio = { version = "1", features = ["full"] }
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"
gethostname = "0.5.0"
rusoto_credential = "0.48.0"
